# Generated by Django 6.0 on 2025-12-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='sacco',
        ),
        migrations.AddField(
            model_name='route',
            name='saccos',
            field=models.ManyToManyField(related_name='routes', to='routes.sacco'),
        ),
    ]
