# Generated by Django 6.0 on 2025-12-09 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='fare',
            new_name='base_fare',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sacco',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'MPESA'), ('CASH', 'Cash'), ('BOTH', 'MPESA & Cash')], default='MPESA', max_length=10),
        ),
    ]
