# Generated by Django 6.0 on 2025-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_review_options_alter_stop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={},
        ),
        migrations.RemoveField(
            model_name='stop',
            name='order',
        ),
        migrations.AddField(
            model_name='stop',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
